"""Data models for call requests and responses."""

from pydantic import BaseModel, Field


class CallRequest(BaseModel):
    """Inbound message payload sent by a caller simulation."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="The caller's message in plain text.",
    )


class CallResponse(BaseModel):
    """Response generated by the assistant for a call."""

    caller_message: str
    ai_response: str
    matched_intent: str
